apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-h2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-h2
  template:
    metadata:
      labels:
        app: my-h2
    spec:
      containers:
        - name: my-h2
          image: jp.icr.io/t18-lin-ns/h2db:1.0
          imagePullPolicy: Always
          command:
          ports:
            - containerPort: 8082
            - containerPort: 9092
---
kind: Service
apiVersion: v1
metadata:
  name: my-h2-service
spec:
  type: NodePort
  selector:
    app: my-h2
  ports:
    - name: web-console
      protocol: TCP
      port: 8082
      targetPort: 8082
    - name: external-access
      protocol: TCP
      port: 9092
      targetPort: 9092
            